# fly.toml app configuration file generated for lt-dust-ai-server on 2024-01-12T11:17:40-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lt-dust-ai-server"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
