# fly.toml app configuration file generated for lt-dust on 2023-10-10T19:39:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lt-dust"
primary_region = "sea"

[deploy]
  release_command = "npm run db:migrate:prod"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
